# Generated by Django 5.2.17 on 2026-08-15 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(editable=False, max_length=100, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='businesses/logos/')),
                ('description', models.TextField(blank=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=15)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('opening_hours', models.CharField(blank=True, max_length=255)),
                ('currency', models.CharField(default='FCFA', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('suspended', 'Suspendu')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'commerce',
                'verbose_name_plural': 'commerces',
                'ordering': ['name'],
            },
        ),
    ]
