# Generated by Django 5.2.17 on 2026-08-16 17:22

import apps.businesses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.businesses.models.business_logo_upload_to),
        ),
    ]
