# Generated by Django 5.2.17 on 2026-08-16 18:33

import apps.businesses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_alter_business_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=15, validators=[apps.businesses.models.validate_whatsapp_number]),
        ),
    ]
